name: Static Analysis

on:
  push:
  pull_request:
    branches: [master]

jobs:
  luacheck:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install luacheck
        run: |
          curl https://github.com/lunarmodules/luacheck/releases/download/v1.2.0/luacheck -o luacheck --verbose --location
          chmod +x luacheck

      - name: Perform static analysis
        run: ./luacheck .
